config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'boards#index'
  resources :boards, only: %i(new index create show destroy)
  resources :list, only: %i(new create edit update destroy) do
    resources :card, except: %i(index)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many   :lists, dependent: :destroy  
  validates  :title, length: { in: 1..255 }
  
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to   :list
  acts_as_list  scope: :list
  validates    :title, length: { in: 1..255 }
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many   :cards, -> {order(position: :asc)}, dependent: :destroy
  validates  :title, length: { in: 1..255 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  has_many :lists, dependent: :destroy
  has_many :boards

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
before_action :set_board, only: %i(show destroy)

  def index
    @boards = Board.all
  end
  
  def new
    @board = Board.new
    @user = User.find_by(id: current_user.id)
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to :boards
    else
      @board.valid?
      render action: :new
    end
  end

  def show
    @lists = List.where(board_id: params[:id]).includes(:cards)
  end

  def destroy
    @board.destroy
    redirect_to :boards
  end

  private
  def board_params
    params.require(:board).permit(:title, :detail, :user_id).merge(user: current_user)
  end

  def set_board
    @board = Board.find_by(id: params[:id])
  end
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  before_action :set_card, only: %i(show edit update destroy)

  def new
    @card = Card.new
    # includesで@boardを関連でもってこれそう
    @list = List.find_by(id: params[:list_id])  
    @board = Board.find_by(id: @list[:board_id])
  end

  def create
    @card = Card.new(card_params)
    @list = List.find_by(id: params[:list_id])
    if @card.save
      redirect_to board_path(id: @list.board_id)
    else
      @card.valid?
      render action: :new
    end
  end

  def show
  end

  def edit
    @lists = List.where(user: current_user)
  end

  def update
    if @card.update_attributes(card_params)
      redirect_to :root
    else
      @card.valid?
      render action: :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to :root
  end

  private
  def card_params
    params.require(:card).permit(:title, :memo, :list_id)
  end

  def set_card
    @card = Card.find_by(id: params[:id])
  end

  # def set_board
  #   @board = Board.find_by(id: params[:id])
  # end

end

app/controllers/list_controller.rb
class ListController < ApplicationController
  before_action :set_list, only: %i(edit update destroy)
  # before_action :set_board, only: %i(create)

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to board_path(id: @list.board_id)
    else
      @list.valid?
      render action: :new
    end
  end

  def edit
  end

  def update
    if @list.update_attributes(list_params)
      redirect_to board_path(id: @list.board_id)
    else
      @list.valid?
      render action: :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to board_path(id: @list.board_id)
  end

  private
  def list_params
    params.require(:list).permit(:title, :board_id).merge(user: current_user)
  end

  def set_list
    @list = List.find_by(id: params[:id])
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @lists = List.where(id: board_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/boards/index.html.erb
<div class="boardsListWrapper container-fluid ">
  
  <!------------------ 左側ボードリスト ----------------->
  <div class="boardsList col-md-9">
    <% @boards.each do |board| %>
      <div class="board bg-success">
        <h1 class="boardTitle text-center">
          <!-- FIXME: マイページに移すか作成者のみ削除できるように要変更 -->
          <%= link_to "#{board.title}", board_path(board.id) %>
          <%= link_to content_tag(:i, '', class: 'fas fa-trash'), board, method: :delete, data: {confirm: "#{board.title}を削除して大丈夫ですか？" } %>
        </h1><!-- /.boardTitle -->
        
        <p class="boardDetail text-center">
          <%= board.detail %>
        </p><!-- /.boardDetail -->
      </div><!-- /.board -->
    <% end %>
  </div><!-- /.boardsList -->

  <!-------------------右側サイドバー---------------------->
  <div class="rankingBar col-md-3 ">
    <h1 class="rankingTitle text-center">
      月間ランキング
    </h1><!-- /.rankingTitle -->
    <% @boards.each.with_index(1) do |board, i| %>
      <div class="rankingCard card bg-success h-25">
        <h1 class="boardTitle text-center">
          <%= i.to_s + board.title %>
        </h1><!-- /.boardTitle -->
        <p class="boardDetail text-center">
          <%= board.detail %>
        </p><!-- /.boardDetail -->
      </div><!-- /.board -->
    <% end %>
  </div><!-- /.sideBar -->

</div><!-- /.container-fluid -->

app/views/boards/new.html.erb
<div class="boardnewPage">
  <div class="container">
    <%= form_with model: @board, url: { action: :create }, html: { class: "boardnewForm" } do |f| %>
      <% if @board.errors.any? %>
        <p class="text-danger">タイトルは1~255文字以内で入力してください</p>
      <% end %>
      <div class="text-center cardnewForm_title">
        <%= f.label :title %>
        <%= f.text_area :title, autofocus: true, class: "form-control", placeholder: "タイトル" %>
      </div> <%# cardnewForm %>
      <div class="text-center">
        <%= f.label :detail %>
        <%= f.text_area :detail, autofocus: true, class: "form-control", placeholder: "詳細" %>
        <div class="text-center"><%= f.submit "作成する", class: "submitBtn" %></div>
      </div> <%# text-center %>
    <% end %>
  </div> <%# container %>
</div> <%# cardnewPage %>

app/views/boards/show.html.erb
<div class="topPage">

  <div class="listWrapper">
    <% @lists.each do |list| %>
      <div class="list">
        <div class="list_header">
          <h2 class="list_header_title"><%= list.title %></h2>
          <div class="list_header_action">
            <%= link_to content_tag(:i, '', class: 'fas fa-trash'), list, method: :delete, data: {confirm: "#{list.title}を削除して大丈夫ですか？" } %>
            <%= link_to content_tag(:i, '',class: 'fas fa-pen'), edit_list_path(list) %>
          </div>
        </div> <%# list_header %>

        <%# リスト内にカードを表示 %>
        <div class="cardWrapper", id="sortableList">
          <% list.cards.each do |card| %>
            <%= link_to list_card_path(list, card), class:"cardDetail_link" do %>
              <div class="card">
                <h3 class="card_title"><%= card.title %></h3>
                <% if card.memo.size > 0 %>
                  <div class="card_detail is-exist">
                    <i class="fas fa-bars"></i>
                  </div>
                <% end %>
              </div> <%# card %>
            <% end %> <%# link_to %>
          <% end %> <%# list.cards.each %>
        </div> <%# cardWrapper %>

        <div class="addCard">
          <i class="far fa-plus-square"></i>
          <%= link_to "さらにカードを追加", new_list_card_path(list), class: "addCard_link" %>
        </div> <%# addCard %>
        
      </div> <%# list %>

    <% end %> <%# @lists.each %>
  </div> <%# listWrapper %>
  
</div> <%# topPage %>

app/views/card/edit.html.erb
<div class="cardeditPage">
  <div class="container">
    <%= form_with model: @card, url: { action: :update }, html: { class: "cardeditForm" } do |f| %>
      
      <% if @card.errors.any? %>
        <p class="text-danger">タイトルは1~255文字以内で入力してください</p><!-- /.text-danger -->
      <% end %>

      <div class="cardeditForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "カード名" %>
      </div><!-- /.cardeditForm_title -->

      <div class="cardeditForm_memo">
        <%= f.label :memo %>
        <%= f.text_area :memo, class: "form-control", placeholder: "詳細" %>
      </div><!-- /.cardeditForm_memo -->

      <div class="cardeditForm_memo">
        <label>リスト名</label>
        <%= select :card, :list_id, @lists.map{ |lis| [lis.title, lis.id] }, {}, { class: "form-control" } %>
      </div><!-- /.cardeditForm_memo -->

      <div class="text-center">
        <%= f.submit "更新する", class: "submitBtn" %>
      </div><!-- /.text-center -->
    <% end %>
  </div><!-- /.container -->
</div><!-- /.cardeditPage -->

app/views/card/new.html.erb
<div class="cardnewPage">
  <div class="container">
    <%= form_with model: @card, url: { action: :create }, html: { class: "cardnewForm" } do |f| %>
      <%# ↓FIXME: セキュリティ的に非推奨↓ %>
      <%= f.hidden_field :list_id, value: @list.id %> 
      <% if @card.errors.any? %>
        <p class="text-danger">タイトルは1~255文字以内で入力してください</p>
      <% end %>
      <div class="text-center cardnewForm_title">
        <%= f.label :title %>
        <%= f.text_area :title, autofocus: true, class: "form-control", placeholder: "タイトル" %>
      </div> <%# cardnewForm %>
      <div class="text-center">
        <%= f.label :memo %>
        <%= f.text_area :memo, autofocus: true, class: "form-control", placeholder: "詳細" %>
        <div class="text-center"><%= f.submit "作成する", class: "submitBtn" %></div>
      </div> <%# text-center %>
    <% end %>
  </div> <%# container %>
</div> <%# cardnewPage %>

app/views/card/show.html.erb
<div class="carddetailPage">
  <div class="container">
    <div class="cardContents">

      <div class="cardContents_title">
        <div>タイトル</div>
        <h2><%= @card.title %></h2>
      </div><!-- /.cardContents_title -->

      <div class="cardContents_memo">
        <div>メモ</div>
        <div><%= @card.title %></div>
      </div><!-- /.cardContents_memo -->

      <div class="cardContents_listStatus">
        <div>リスト名</div>
        <div><%= @card.list.title %></div>
      </div><!-- /.cardContents_listStatus -->

      <div class="cardContents_btnArea">
        <%= link_to "編集する", edit_list_card_path(@card.list, @card), class: "edit_btn" %>

        <%= link_to "削除をする", list_card_path(@card.list, @card), class: "text-danger delete_btn", method: :delete, data: { confirm: "このカードを削除して大丈夫ですか?" } %>
      </div><!-- /.cardContents_btnArea -->
    </div><!-- /.cardContents -->
  </div><!-- /.container -->
</div><!-- /.carddetailPage -->

app/views/layouts/_header.html.erb
<nav class="myHeader navbar navbar-expand-lg navbar-light static-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <%= link_to "TaskHub", root_path, class: "navbar-brand title" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to 'リストを作成', new_list_path(id: params[:id]), class: "nav-link"%>

          </li>
          <li class="nav-item active">
            <%= link_to 'ボードを作成', new_board_path, class: "nav-link"%>
          </li>
          <li class="nav-item active">
            <%= link_to 'ボード一覧', boards_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%=  link_to "#{current_user.name}", root_path, class: "nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskHub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if flash[:notice] %>
    <div class="alert alert-info"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert alert-danger"><%= flash[:alert] %></div>
  <% end %>

  <% if user_signed_in? %>
    <%= render partial: "layouts/header" %>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/list/create.html.erb
<h1>List#create</h1>
<p>Find me in app/views/list/create.html.erb</p>

app/views/list/edit.html.erb
<div class="listeditPage">
  <div class="container">
    <%= form_with model: @list, url: { action: :update }, html: { class: "listForm" } do |f| %>
      <% if @list.errors.any? %>
        <p class="text-danger">タイトルは1〜255文字で入力してください</p>
      <% end %>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control listName", placeholder: "リスト名" %>
      <div class="text-center"><%= f.submit "編集する", class: "submitBtn" %></div>
    <% end %>
  </div> <%# container %>
</div> <%# listeditPage %>

app/views/list/new.html.erb
<div class="listnewPage">
  <div class="conteiner">
    <%= form_with model: @list, url: { action: :create }, class: "new_list" do |f| %>
      <% if @list.errors.any? %>
        <p class="text-danger">タイトルは255字以内で入力してください</p>
      <% end %>
      <%= f.label :title %>
      <%= f.text_field :title, autufocus: true, class: "form-control listName", placeholder: "リスト名" %>
      <%= f.hidden_field :board_id, value: params[:id] %> 
      <div class="text-center"><%= f.submit "作成", class: "submitBtn" %></div>
    <% end %>
  </div> <%# container %>
</div> <%# listnewPage %>